name: Connection Utility build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        include:
          - os: 'ubuntu-latest'
            distPath: /connection-utility/build/native/nativeCompile/connection-utility
            label: 'linux'
          - os: 'macos-latest'
            distPath: /connection-utility/build/native/nativeCompile/connection-utility
            label: 'mac'
          - os: 'windows-latest'
            distPath: \connection-utility\build\native\nativeCompile\connection-utility.exe
            label: 'windows'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: 'Build Executable'
        run: ./gradlew clean nativeCompile
      - name: Archive Executable
        uses: actions/upload-artifact@v4
        with:
          name: connection-utility-${{ matrix.label }}
          path: ${{ github.workspace }}${{ matrix.distPath }}
          retention-days: 14